//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.25 at 08:09:53 PM GMT+03:00 
//


package userssoap.model;

import userssoap.CreateNewUserRequest;
import userssoap.EditUserRequest;
import userssoap.GetUserRequest;
import userssoap.GetUserResponse;
import userssoap.GetUsersResponse;
import userssoap.RemoveUserRequest;
import userssoap.Role;
import userssoap.User;
import userssoap.UserDto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the userssoap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: userssoap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link userssoap.EditUserRequest }
     * 
     */
    public userssoap.EditUserRequest createEditUserRequest() {
        return new EditUserRequest();
    }

    /**
     * Create an instance of {@link userssoap.User }
     * 
     */
    public userssoap.User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link userssoap.GetUserResponse }
     * 
     */
    public userssoap.GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link OperationResponse }
     * 
     */
    public OperationResponse createOperationResponse() {
        return new OperationResponse();
    }

    /**
     * Create an instance of {@link userssoap.GetUserRequest }
     * 
     */
    public userssoap.GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link userssoap.CreateNewUserRequest }
     * 
     */
    public userssoap.CreateNewUserRequest createCreateNewUserRequest() {
        return new CreateNewUserRequest();
    }

    /**
     * Create an instance of {@link userssoap.RemoveUserRequest }
     * 
     */
    public userssoap.RemoveUserRequest createRemoveUserRequest() {
        return new RemoveUserRequest();
    }

    /**
     * Create an instance of {@link userssoap.GetUsersResponse }
     * 
     */
    public userssoap.GetUsersResponse createGetUsersResponse() {
        return new GetUsersResponse();
    }

    /**
     * Create an instance of {@link userssoap.UserDto }
     * 
     */
    public userssoap.UserDto createUserDto() {
        return new UserDto();
    }

    /**
     * Create an instance of {@link userssoap.Role }
     * 
     */
    public userssoap.Role createRole() {
        return new Role();
    }

}
